[DRAFT] Feat/mynw 111 private shard support
mynearwallet/near-wallet pull request #1
Opened 2022-07-29 21:01 UTC by followdarko

Context:
https://docs.google.com/document/d/1iU2uu_63wFqwWuypCCcpLxeKZtSy8gxpvOQXS8ZPvuk/edit
https://www.notion.so/kikimora-labs/Private-Shards-Support-43663afa7bfb41bba8afb21a92857a16
Jira https://mnw.atlassian.net/browse/MYNW-111

2022-09-01 14:01 UTC, xilosada requested changes
This is great I used it as base and opened a PR with the changes required to make it work e2e

2022-09-01 14:01 UTC, xilosada commented on packages/frontend/src/utils/wallet.js
> +            const [, signedTransaction] = await nearApiJs.transactions.signTransaction(receiverId, nonce, actions, blockHash, calimeroConnection.signer, accountId, NETWORK_ID);
signer not defined

2022-09-07 14:20 UTC, followdarko commented on packages/frontend/src/utils/wallet.js
> +        const calimeroConnection = nearApiJs.providers.JsonRpcProvider(customRPCUrl);
@xilosada I'm sorry where did you replaced it?

2022-09-07 14:33 UTC, followdarko commented on packages/frontend/src/utils/wallet.js
> +        const calimeroConnection = nearApiJs.providers.JsonRpcProvider(customRPCUrl);
I updated to `nearApiJs.Connection.fromConfig`
Not sure about `x-api-token` header thought

2022-09-08 17:46 UTC, xilosada commented
@followdarko We will address all these questions after Nearcon.

2022-09-08 17:52 UTC, PinkiNice commented
- Should we do anything with icon and colours of shard in UI?
Out of scope for now
 - Tooltip text for private shard info in UI
 "Private shard transactions are executed inside private shard environment. They will not affect you main account."
- Should private shard RPC url be a link?
No, lets make it just a text
- Should we add additional check where account id ends with private shard id?
We should check "signer" and "receiver" in transaction to be under "private-shard-id" scope
- If account that not belongs to private shard try to sign a transaction to it what should we display?
Signing account always will be .testnet or .mainnet  (not private shard). So it is ok
- We should add analytics to sign transactions on private shards.
Out of scope for now

2022-09-08 20:43 UTC, followdarko commented
@xilosada is it ok display full path rpc url or should we make it shorter?
<img width="452" alt="Screenshot 2022-09-08 at 23 41 09" src="https://user-images.githubusercontent.com/7001916/189221812-486c9c7f-a91c-4f2d-9d4d-379620c8b971.png">

2022-10-09 12:51 UTC, merged