MNW add Prettier
mynearwallet/near-wallet pull request #58
Opened 2022-10-21 16:29 UTC by NotEternal

2022-10-21 16:34 UTC, loosefer approved these changes

2022-10-24 09:22 UTC, followdarko commented on packages/frontend/.prettierrc
> +    "tabWidth": 4,
4 -> 2

2022-10-24 09:23 UTC, followdarko requested changes
let's change "tabWidth": 4 => 2

2022-10-24 09:34 UTC, followdarko approved these changes

2022-10-24 11:17 UTC, merged